### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by maxmechanic**
Update Jest and React, add ReactDOM, and testing against more recent Node versions.

### CODE REVIEW

**Comment by clayallsopp** [comment]
This is pretty awesome - can you bump the package.json version as well? to 0.7?

**Comment by markijbema** [comment]
Wow, great! Thanks so much!

**Comment by markijbema** [comment]
@clayallsopp should we include the currently supported versions of backbone and react in the readme?

**Comment by clayallsopp** [comment]
@markijbema added: https://github.com/clayallsopp/react.backbone/commit/a618e2a8cdcb3ab78c283e71b90431f532c0ca05

thanks again @maxmechanic !

**Pull request merged**
