### PR TITLE
component.isMounted() is deprecated

### PR DESCRIPTION
**Pull request by workshur**
Adds own _isMounted property

### CODE REVIEW

**Comment by markijbema** [comment]
This look good to me, thanks! @clayallsopp can you push this to npm?

**Comment by clayallsopp** [comment]
@markijbema do you have an NPM account? would prefer to add you as a collab for the release

**Comment by markijbema** [comment]
I do now, same as my github username

**Comment by clayallsopp** [comment]
@markijbema done! :shipit:

**Pull request merged**
